spring:
  application:
    name: rate-limiter-example
  data:
    redis:
      url: ${TEST_REDIS_ADDRESS:redis://127.0.0.1:6379}
server:
  address: 127.0.0.1
  port: ${SERVER_PORT:18090}
multi-redis:
  enabled: true
  clients:
    main:
      address: ${TEST_REDIS_ADDRESS:redis://127.0.0.1:6379}
management:
  endpoints:
    web:
      exposure:
        include: health
